# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: records.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='records.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\rrecords.proto\"\x0e\n\x0c\x45mptyMessage\"\x1b\n\x0bNameMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x11ListFilesResponse\x12\r\n\x05\x66iles\x18\x01 \x03(\t\"!\n\x10\x46indFileResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x32>\n\x0c\x46ilesService\x12.\n\tListFiles\x12\r.EmptyMessage\x1a\x12.ListFilesResponse2@\n\x10\x46indFilesService\x12,\n\tFindFiles\x12\x0c.NameMessage\x1a\x11.FindFileResponseb\x06proto3'
)


_EMPTYMESSAGE = _descriptor.Descriptor(
    name='EmptyMessage',
    full_name='EmptyMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=17,
    serialized_end=31,
)


_NAMEMESSAGE = _descriptor.Descriptor(
    name='NameMessage',
    full_name='NameMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='name', full_name='NameMessage.name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=33,
    serialized_end=60,
)


_LISTFILESRESPONSE = _descriptor.Descriptor(
    name='ListFilesResponse',
    full_name='ListFilesResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='files', full_name='ListFilesResponse.files', index=0,
            number=1, type=9, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=62,
    serialized_end=96,
)


_FINDFILERESPONSE = _descriptor.Descriptor(
    name='FindFileResponse',
    full_name='FindFileResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='found', full_name='FindFileResponse.found', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=98,
    serialized_end=131,
)

DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['NameMessage'] = _NAMEMESSAGE
DESCRIPTOR.message_types_by_name['ListFilesResponse'] = _LISTFILESRESPONSE
DESCRIPTOR.message_types_by_name['FindFileResponse'] = _FINDFILERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
    'DESCRIPTOR': _EMPTYMESSAGE,
    '__module__': 'records_pb2'
    # @@protoc_insertion_point(class_scope:EmptyMessage)
})
_sym_db.RegisterMessage(EmptyMessage)

NameMessage = _reflection.GeneratedProtocolMessageType('NameMessage', (_message.Message,), {
    'DESCRIPTOR': _NAMEMESSAGE,
    '__module__': 'records_pb2'
    # @@protoc_insertion_point(class_scope:NameMessage)
})
_sym_db.RegisterMessage(NameMessage)

ListFilesResponse = _reflection.GeneratedProtocolMessageType('ListFilesResponse', (_message.Message,), {
    'DESCRIPTOR': _LISTFILESRESPONSE,
    '__module__': 'records_pb2'
    # @@protoc_insertion_point(class_scope:ListFilesResponse)
})
_sym_db.RegisterMessage(ListFilesResponse)

FindFileResponse = _reflection.GeneratedProtocolMessageType('FindFileResponse', (_message.Message,), {
    'DESCRIPTOR': _FINDFILERESPONSE,
    '__module__': 'records_pb2'
    # @@protoc_insertion_point(class_scope:FindFileResponse)
})
_sym_db.RegisterMessage(FindFileResponse)


_FILESSERVICE = _descriptor.ServiceDescriptor(
    name='FilesService',
    full_name='FilesService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=133,
    serialized_end=195,
    methods=[
        _descriptor.MethodDescriptor(
            name='ListFiles',
            full_name='FilesService.ListFiles',
            index=0,
            containing_service=None,
            input_type=_EMPTYMESSAGE,
            output_type=_LISTFILESRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_FILESSERVICE)

DESCRIPTOR.services_by_name['FilesService'] = _FILESSERVICE


_FINDFILESSERVICE = _descriptor.ServiceDescriptor(
    name='FindFilesService',
    full_name='FindFilesService',
    file=DESCRIPTOR,
    index=1,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=197,
    serialized_end=261,
    methods=[
        _descriptor.MethodDescriptor(
            name='FindFiles',
            full_name='FindFilesService.FindFiles',
            index=0,
            containing_service=None,
            input_type=_NAMEMESSAGE,
            output_type=_FINDFILERESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_FINDFILESSERVICE)

DESCRIPTOR.services_by_name['FindFilesService'] = _FINDFILESSERVICE

# @@protoc_insertion_point(module_scope)
