# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: records.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='records.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rrecords.proto\"\x0e\n\x0c\x45mptyMessage\"!\n\x12PingRecordResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2;\n\x06Record\x12\x31\n\x0bPingRecords\x12\r.EmptyMessage\x1a\x13.PingRecordResponseb\x06proto3'
)




_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=31,
)


_PINGRECORDRESPONSE = _descriptor.Descriptor(
  name='PingRecordResponse',
  full_name='PingRecordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='PingRecordResponse.ack', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['PingRecordResponse'] = _PINGRECORDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'records_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

PingRecordResponse = _reflection.GeneratedProtocolMessageType('PingRecordResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRECORDRESPONSE,
  '__module__' : 'records_pb2'
  # @@protoc_insertion_point(class_scope:PingRecordResponse)
  })
_sym_db.RegisterMessage(PingRecordResponse)



_RECORD = _descriptor.ServiceDescriptor(
  name='Record',
  full_name='Record',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=68,
  serialized_end=127,
  methods=[
  _descriptor.MethodDescriptor(
    name='PingRecords',
    full_name='Record.PingRecords',
    index=0,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_PINGRECORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECORD)

DESCRIPTOR.services_by_name['Record'] = _RECORD

# @@protoc_insertion_point(module_scope)
