version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    container_name: mariadb
    ports:
      - 3306:3306 
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

