version: '3.1'
services:
  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
      - 80:80      
    restart: always
    environment:
      WORDPRESS_DB_HOST: 10.128.0.6
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /mnt/wordpress:/var/www/html

